---
swagger: '2.0'
info:
  title: Forever Alone API
  description: Messages and contacts of a forever alone
  version: "1.0.0"
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /messages:
    get:
      tags:
        - Messages
      description: |
        Retrieve messages
      operationId: retrieveMessages
      responses:
        200:
          description: Messages retrieved
          schema:
            type: array
            items:
              $ref: "#/definitions/Message"
        default:
          description: Operation failed
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - Messages
      description: |
        Create new message
      operationId: createMessage
      parameters:
        - name: message
          in: body
          required: true
          schema:
            $ref: "#/definitions/MessageRequest"
      responses:
        200:
          description: Message created
          schema: 
            type: object
            properties:
              id:
                type: integer
                format: int32
        default:
          description: Operation failed
          schema:
            $ref: "#/definitions/Error"
  /messages/{id}:
    get:
      tags:
        - Messages
      description: |
        Retrieve specific message
      operationId: retrieveMessage
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Message retrieved
          schema:
            $ref: "#/definitions/Message"
        default:
          description: Operation failed
          schema:
            $ref: "#/definitions/Error"
    put:
      tags:
       - Messages
      description: |
        Update specific message
      operationId: updateMessage
      parameters:
        - $ref: "#/parameters/id"
        - name: message
          in: body
          required: true
          schema:
            $ref: "#/definitions/MessageRequest"          
      responses:
        204:
          description: Message updated
        default:
          description: Operation failed
          schema:
            $ref: "#/definitions/Error"
  /contacts:
    get:
      tags:
        - Contacts
      description: |
        Retrieve contacts
      operationId: retrieveContacts
      responses:
        200:
          description: Contacts retrieved
          schema:
            type: array
            items:
              $ref: "#/definitions/Contact"
        default:
          description: Operation failed
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - Contacts
      description: |
        Create new contact
      operationId: createContact
      parameters:
        - name: contact
          in: body
          required: true
          schema:
            $ref: "#/definitions/ContactRequest"
      responses:
        200:
          description: Contact created
          schema: 
            type: object
            properties:
              id:
                type: integer
                format: int32
        default:
          description: Operation failed
          schema:
            $ref: "#/definitions/Error"
  /contacts/{id}:
    get:
      tags:
        - Contacts
      description: |
        Retrieve a specific contact
      operationId: retrieveContact
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Contact retrieved
          schema:
            $ref: "#/definitions/Contact"
        default:
          description: Operation failed
          schema:
            $ref: "#/definitions/Error"
    put:
      tags:
        - Contacts
      description: |
        Update a specific contact
      operationId: updateContact
      parameters:
        - $ref: "#/parameters/id"
        - name: contact
          in: body
          required: true
          schema:
            $ref: "#/definitions/ContactRequest"
      responses:
        204:
          description: Contact updated
        default:
          description: Operation failed
          schema:
            $ref: "#/definitions/Error"
definitions:
  Message:
    type: object
    required:
      - id
      - contact
      - message
    properties:
      id:
        type: integer
        format: int32
      contact:
        $ref: "#/definitions/Contact"
      message:
        type: string
  MessageRequest:
    type: object
    required:
      - contact
      - message
    properties:
      contact: 
        $ref: "#/definitions/Contact"
      message:
        type: string
  Contact:
    type: object
    required:
      - id
      - name
      - contact_no
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
      contact_no:
        type: integer
        format: int64
  ContactRequest:
    type: object
    required:
      - name
      - contact_no
    properties:
      name:
        type: string
      contact_no:
        type: integer
        format: int64
  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
parameters:
  id:
    name: id
    in: path
    required: true
    description: Entity ID
    type: string
    format: int64